### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1643]
> What version of ejabberd are you using?

Source code version 16.09, Community Version

> What operating system (version) are you using?

CentOs7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

connect got reset abruptly at client

> was the unexpected behavior? What was the expected result?

connection should alive till timeout time span

Hi,

I implementing android xmpp client, using Smack library, i am able to establish connection and could send messages through client, but I am getting exception 'connection close with error' very frequently at client side where as at serverside i am not getting any error log, this happens when I keep app 5 min ideal, I never modified s2c connection timeout, its default(10 min) following is an exception 

Connection XMPPTCPConnection[user1@xmpp.testchat.com/MobileApp] (2) closed with error
                                                                                         java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                             at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                                                                                             at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
                                                                                             at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                                                                                             at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                                             at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                             at java.io.InputStream.read(InputStream.java:162)
                                                                                             at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194)
                                                                                             at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
                                                                                             at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                                             at java.io.BufferedReader.read(BufferedReader.java:325)
                                                                                             at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:42)
                                                                                             at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515)
                                                                                             at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992)
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1228)
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980)
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                             at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                             at libcore.io.Posix.recvfrom(Posix.java:189)
                                                                                             at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                                             at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
                                                                                             at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481) 
                                                                                             at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37) 
                                                                                             at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                                                             at java.io.InputStream.read(InputStream.java:162) 
                                                                                             at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194) 
                                                                                             at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153) 
                                                                                             at java.io.InputStreamReader.read(InputStreamReader.java:233) 
                                                                                             at java.io.BufferedReader.read(BufferedReader.java:325) 
                                                                                             at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:42) 
                                                                                             at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515) 
                                                                                             at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992) 
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:349) 
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:313) 
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1228) 
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980) 
                                                                                             at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996) 
                                                                                             at java.lang.Thread.run(Thread.java:818)

Can anyone please help me !

Thanks,
Veer

**Comment by badlop** [comment]
Hi, I can give you some general ideas, maybe they help you a little:
* If you connect with another well known client, it has no problem, right? I mean, try with Gajim, Psi, Pidgin. They aren't disconnected by ejabberd, right?
* Have you noticed ejabberd disconnects your client aways in the same time? I mean, always after 5 minutes, or always after 10 minutes?
* If a TCP connection doesn't have any activity in some minutes, it may be automatically closed by your Operating System. For that reason, some clients and servers implement "keep-alive packets". See https://docs.ejabberd.im/admin/configuration/#mod-ping Try to enable this module with send_pings enabled.
* You can set loglevel 5 in ejabberd, maybe it shows some interesting information when it disconnects your client.
* You can use a network sniffer to see the TCP traffic between your client and ejabberd. It probably doesn't help much, but at least this confirms it is ejabberd who closes your connection: "tcpflow -i lo -Cg port 5222"

**Comment by Veerbhadra277** [comment]
Thanks @badlop , for you reply 

> If you connect with another well known client, it has no problem, right? I mean, try with Gajim, Psi, Pidgin. They aren't disconnected by ejabberd, right?

yes, if I connect through spark, Tkabber clients, it stay connected till we do explicitly logout.

> Have you noticed ejabberd disconnects your client aways in the same time? I mean, always after 5 minutes, or always after 10 minutes?

It disconnects with 5-10 min for sure, if I keep idle for this time. 

> If a TCP connection doesn't have any activity in some minutes, it may be automatically closed by your Operating System. For that reason, some clients and servers implement "keep-alive packets". See https://docs.ejabberd.im/admin/configuration/#mod-ping Try to enable this module with send_pings enabled

I don't want to use this, as it will become overhead for xmpp server and all client will kept online event though they ideal for long time. 

> You can set loglevel 5 in ejabberd, maybe it shows some interesting information when it disconnects your client.

yeah I have done that, and found very frequent related logs as follows
2017-03-30 07:17:31.669 [debug] <0.14882.3>@ejabberd_s2s_in:terminate:599 terminated: normal
2017-03-30 07:17:31.669 [debug] <0.14883.3>@ejabberd_c2s:send_text:1924 Send XML on stream = <<"</stream:stream>">>
2017-03-30 07:17:31.669 [debug] <0.14883.3>@ejabberd_socket:send:184 Error in gen_tcp:send: {error,closed}

do you have any idea why it would happening ?

**Comment by badlop** [comment]
> It disconnects with 5-10 min for sure, if I keep idle for this time.

Then you have two solutions, either implement a ping feature in your client, or enable mod_ping with send_pings in ejabberd. You can start with a long ping_interval (let's say 15 minutes), and reduce it until no client gets disconnected.

> I don't want to use this, as it will become overhead for xmpp server and all client will kept online event though they ideal for long time.

Well, the overhead of such messages is minimal to ejabberd, compared to other tasks like presence broadcast or room messaging. Enable it, and keep an eye in CPU and RAM Consumption.

**Comment by cromain** [comment]
i think badlop covered your questions, closing now.
