### ISSUE TITLE
Updated ejabberd from version 2.1 to 17.07.now can not register a user through android app using smack 4.2.

### ISSUE THREAD

**Issue by kapilo-bharadwaj** [processone/ejabberd#1886]
this is the error coming on client side on android:
Connection XMPPTCPConnection[not-authenticated] (5) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: not-authorized You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1046)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996)
at java.lang.Thread.run(Thread.java:818)
E/ExceptionException: org.jivesoftware.smack.SmackException$NotConnectedException: The connection XMPPTCPConnection[not-authenticated] (5) is no longer connected while waiting for response with StanzaIdFilter: id=jq6OD-18

and when debuging on ejabberd,error is following:
```
[debug] <0.517.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<stream:stream xmlns='jabber:client' to='180.151.230.12' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>">>
2017-07-26 13:57:17.581 [debug] <0.518.0>@ejabberd_socket:send:216 (tcp|<0.517.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='15893217347206381748' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' from='180.151.230.12' xmlns='jabber:client'>">>
2017-07-26 13:57:17.582 [debug] <0.518.0>@ejabberd_socket:send:216 (tcp|<0.517.0>) Send XML on stream = <<"<stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>X-OAUTH2</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><auth xmlns='http://jabber.org/features/iq-auth'/></stream:features>">>
2017-07-26 13:57:17.665 [debug] <0.517.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<iq to='180.151.230.12' id='iil9d-9' type='get'><query xmlns='jabber:iq:register'></query></iq>">>
2017-07-26 13:57:17.665 [debug] <0.517.0>@shaper:update:143 State: {maxrate,1000,0.0,1501057637582048}, Size=95
M=47.5, I=83.325
2017-07-26 13:57:17.665 [debug] <0.518.0>@ejabberd_socket:send:216 (tcp|<0.517.0>) Send XML on stream = <<"<stream:error><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>">>
2017-07-26 13:57:17.665 [debug] <0.518.0>@ejabberd_socket:send:216 (tcp|<0.517.0>) Send XML on stream = <<"</stream:stream>">>
```

**Comment by zinid** [comment]
You don't have `mod_register` loaded.
