### ISSUE TITLE
ejabberd18.04 with MySQL  SASLError using SCRAM-SHA-1: not-authorized

### ISSUE THREAD

**Issue by wqxcloud** [processone/ejabberd#2435]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-85-generic x86_64)

> How did you install ejabberd (source, package, distribution)?

./ejabberd-18.04-linux-x86_64-installer.run

> What did not work as expected? 
after 7 hours about,i can`t login with the same account and password when i install ejabberd18.04

Hi，I need your help,please
when i install the ejabberd successful, not to start it. i edit the ejabberd.yml as follow to use mysql 5.7 ,then  i start ejabberd, then register account and admin in  localhost  servicer,  there are accounts in  mysql  table of user, i login account with android mobile with internet(not wifi),i can successful login.
but after half day(7 hours about),i can't login with the same account and password（plain），such as  account: 123456   pwd:123456aaa, information as follows, can you help me,best wish

ejabberd.yml
```
auth_mothod: sql
default_db: sql

     sql_type: mysql
     sql_server: ""
     sql_database: "e"
     sql_username: ""
     sql_password: ""
```

> Arethere error messages in the log? 

```
exception
05-24 12:30:35.740 24600-24698/com.wqx.dowa I/XmppService: LogUtils:XXException e=com.wqx.dowa.exception.XXException: SASLError using SCRAM-SHA-1: not-authorized
05-24 12:30:35.741 24600-24698/com.wqx.dowa I/com.wqx.dowa.service.XmppService: LogUtils:XMPPException in doConnect():
05-24 12:30:35.741 24600-24698/com.wqx.dowa W/System.err: com.wqx.dowa.exception.XXException: SASLError using SCRAM-SHA-1: not-authorized
05-24 12:30:35.742 24600-24698/com.wqx.dowa W/System.err:     at com.wqx.dowa.smack.SmackImpl.login(SmackImpl.java:536)
05-24 12:30:35.742 24600-24698/com.wqx.dowa W/System.err:     at com.wqx.dowa.service.XmppService$1.run(XmppService.java:230)
05-24 12:30:35.748 24600-24600/com.wqx.dowa I/LoginActivity: LogUtils:LoginActivity connectionStatusChanged connectedState=-1
05-24 12:30:35.748 24600-24600/com.wqx.dowa I/LoginActivity: LogUtils:LoginActivity connectionStatusChanged reason=SASLError using SCRAM-SHA-1: not-authorized
05-24 12:30:35.875 23178-24436/? I/SendBroadcastPermission: action:com.taobao.accs.intent.action.CONNECTINFO, mPermissionType:0
```

ejabberd.log
```
2018-05-25 19:42:11.895 [error] <0.471.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.486.0>,normal}
2018-05-25 19:42:11.896 [error] <0.972.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:42:11.896 [info] <0.972.0>@ejabberd_c2s:handle_auth_failure:444 (tcp|<0.972.0>) Failed c2s SCRAM-SHA-1 authentication for 100000@123.56.30.171 from ::ffff:223.223.196.168: Invalid username or password
2018-05-25 19:47:33.373 [info] <0.407.0>@ejabberd_listener:accept:302 (<0.978.0>) Accepted connection ::ffff:223.223.196.168:50355 -> ::ffff:172.17.181.14:5280
2018-05-25 19:47:38.833 [info] <0.407.0>@ejabberd_listener:accept:302 (<0.979.0>) Accepted connection ::ffff:223.223.196.168:50367 -> ::ffff:172.17.181.14:5280
2018-05-25 19:47:46.388 [info] <0.407.0>@ejabberd_listener:accept:302 (<0.980.0>) Accepted connection ::ffff:223.223.196.168:50378 -> ::ffff:172.17.181.14:5280
2018-05-25 19:47:46.388 [info] <0.407.0>@ejabberd_listener:accept:302 (<0.981.0>) Accepted connection ::ffff:223.223.196.168:50379 -> ::ffff:172.17.181.14:5280
2018-05-25 19:47:47.972 [error] <0.472.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.487.0>,normal}
2018-05-25 19:47:47.972 [error] <0.981.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:47:47.972 [warning] <0.981.0>@ejabberd_web_admin:process:234 Access of <<"admin">> from <<"::ffff:223.223.196.168">> failed with error: <<"inexistent-account">>
```

```
root@xu:/opt/ejabberd/logs# tail -f error.log 
2018-05-25 19:42:02.262 [error] <0.468.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.483.0>,normal}
2018-05-25 19:42:02.262 [error] <0.969.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:42:06.306 [error] <0.469.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.484.0>,normal}
2018-05-25 19:42:06.306 [error] <0.970.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:42:09.136 [error] <0.470.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.485.0>,normal}
2018-05-25 19:42:09.136 [error] <0.971.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:42:11.895 [error] <0.471.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.486.0>,normal}
2018-05-25 19:42:11.896 [error] <0.972.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"
2018-05-25 19:47:47.972 [error] <0.472.0>@ejabberd_sql:log:950 p1_mysql_conn: p1_mysql_recv: socket was closed {<0.487.0>,normal}
2018-05-25 19:47:47.972 [error] <0.981.0>@ejabberd_sql:check_error:1100 SQL query 'Q90173024' at {ejabberd_auth_sql,152} failed: "p1_mysql_recv: socket was closed"`
```

> What was the unexpected behavior?

SASLError using SCRAM-SHA-1: not-authorized

> What was the expected result?

login successful

**Comment by badlop** [comment]
So, the connection to the MySQL server gets closed sometime between ejabberd start and the next time you attempt to login. Ideas so you can investigate the problem in your machine:
* Check in the logs if the connection gets closed at a fixed time. 
* Check if you can login correctly between those hours. 
* Also check if the connection lives longer if you login between, or if it's closed always after X fixed hours.

**Comment by zinid** [comment]
Closed due to author inactivity
