### ISSUE TITLE
mod_http_upload ssl handshake error after certificate switch

### ISSUE THREAD

**Issue by MEschenbacher** [processone/ejabberd#2865]
I am experiencing ssl handshake errors on both of my xmpp clients (gajim and conversations) when using the `mod_http_upload` feature after changing my non-wildcard tls cert for a wildcard cert and **reloading** ejabberd. **Restarting** ejabberd will fix the issue.

Steps to reproduce:
 - set up `mod_http_upload` with tls options and valid cert for all the required domains
 - verify it works
 - replace the cert with a wildcard cert for the domain
 - **reload** ejabberd
 - verify uploading does no longer work
 - **restart** ejabberd
 - verify uploading works

Before restarting ejabberd, I tried:
 - Reconnecting xmpp clients
 - Restarting xmpp clients

ejabberd version: `18.12.1-2~bpo9+1` (debian stretch-backports)

# ejabberd debug log
```
2019-04-18 09:29:31.296 [info] <0.16224.8> (tls|<0.16224.8>) Received XML on stream = <<"<iq xmlns=\"jabber:client\" to=\"upload.<redacted>.de\" type=\"get\" id=\"a2e76495-0162-4acf-94e3-2669f81d5287\" from=\"max@<redacted>.de/gajim.8DJQHROQ\"><request xmlns=\"urn:xmpp:http:upload:0\" filename=\"entropy.py\" size=\"1965\" content-type=\"text/x-python\" /></iq>">>
2019-04-18 09:29:31.297 [debug] <0.16224.8>@ejabberd_router:do_route:353 route:
#iq{id = <<"a2e76495-0162-4acf-94e3-2669f81d5287">>,type = get,
    lang = <<"en">>,
    from = #jid{user = <<"max">>,server = <<"<redacted>.de">>,
                resource = <<"gajim.8DJQHROQ">>,luser = <<"max">>,
                lserver = <<"<redacted>.de">>,lresource = <<"gajim.8DJQHROQ">>},
    to = #jid{user = <<>>,server = <<"upload.<redacted>.de">>,resource = <<>>,
              luser = <<>>,lserver = <<"upload.<redacted>.de">>,lresource = <<>>},
    sub_els = [#xmlel{name = <<"request">>,
                      attrs = [{<<"xmlns">>,<<"urn:xmpp:http:upload:0">>},
                               {<<"filename">>,<<"entropy.py">>},
                               {<<"size">>,<<"1965">>},
                               {<<"content-type">>,<<"text/x-python">>}],
                      children = []}],
    meta = #{ip => {10753,1184,89,4096,0,0,0,19}}}
2019-04-18 09:29:31.297 [info] <0.464.0>@mod_http_upload:create_slot:596 Got HTTP upload slot for max@<redacted>.de/gajim.8DJQHROQ (file: entropy.py, size: 1965)
2019-04-18 09:29:31.297 [debug] <0.464.0>@ejabberd_router:do_route:353 route:
#iq{id = <<"a2e76495-0162-4acf-94e3-2669f81d5287">>,type = result,
    lang = <<"en">>,
    from = #jid{user = <<>>,server = <<"upload.<redacted>.de">>,resource = <<>>,
                luser = <<>>,lserver = <<"upload.<redacted>.de">>,lresource = <<>>},
    to = #jid{user = <<"max">>,server = <<"<redacted>.de">>,
              resource = <<"gajim.8DJQHROQ">>,luser = <<"max">>,
              lserver = <<"<redacted>.de">>,lresource = <<"gajim.8DJQHROQ">>},
    sub_els = [#upload_slot_0{get = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              put = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              xmlns = <<"urn:xmpp:http:upload:0">>}],
    meta = #{ip => {10753,1184,89,4096,0,0,0,19}}}
2019-04-18 09:29:31.297 [debug] <0.464.0>@ejabberd_local:do_route:142 local route:
#iq{id = <<"a2e76495-0162-4acf-94e3-2669f81d5287">>,type = result,
    lang = <<"en">>,
    from = #jid{user = <<>>,server = <<"upload.<redacted>.de">>,resource = <<>>,
                luser = <<>>,lserver = <<"upload.<redacted>.de">>,lresource = <<>>},
    to = #jid{user = <<"max">>,server = <<"<redacted>.de">>,
              resource = <<"gajim.8DJQHROQ">>,luser = <<"max">>,
              lserver = <<"<redacted>.de">>,lresource = <<"gajim.8DJQHROQ">>},
    sub_els = [#upload_slot_0{get = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              put = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              xmlns = <<"urn:xmpp:http:upload:0">>}],
    meta = #{ip => {10753,1184,89,4096,0,0,0,19}}}
2019-04-18 09:29:31.298 [debug] <0.464.0>@ejabberd_sm:do_route:684 processing packet to full JID:
#iq{id = <<"a2e76495-0162-4acf-94e3-2669f81d5287">>,type = result,
    lang = <<"en">>,
    from = #jid{user = <<>>,server = <<"upload.<redacted>.de">>,resource = <<>>,
                luser = <<>>,lserver = <<"upload.<redacted>.de">>,lresource = <<>>},
    to = #jid{user = <<"max">>,server = <<"<redacted>.de">>,
              resource = <<"gajim.8DJQHROQ">>,luser = <<"max">>,
              lserver = <<"<redacted>.de">>,lresource = <<"gajim.8DJQHROQ">>},
    sub_els = [#upload_slot_0{get = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              put = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              xmlns = <<"urn:xmpp:http:upload:0">>}],
    meta = #{ip => {10753,1184,89,4096,0,0,0,19}}}
2019-04-18 09:29:31.298 [debug] <0.464.0>@ejabberd_sm:do_route:708 sending to process <0.16224.8>:
#iq{id = <<"a2e76495-0162-4acf-94e3-2669f81d5287">>,type = result,
    lang = <<"en">>,
    from = #jid{user = <<>>,server = <<"upload.<redacted>.de">>,resource = <<>>,
                luser = <<>>,lserver = <<"upload.<redacted>.de">>,lresource = <<>>},
    to = #jid{user = <<"max">>,server = <<"<redacted>.de">>,
              resource = <<"gajim.8DJQHROQ">>,luser = <<"max">>,
              lserver = <<"<redacted>.de">>,lresource = <<"gajim.8DJQHROQ">>},
    sub_els = [#upload_slot_0{get = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              put = <<"https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py">>,
                              xmlns = <<"urn:xmpp:http:upload:0">>}],
    meta = #{ip => {10753,1184,89,4096,0,0,0,19}}}
2019-04-18 09:29:31.298 [debug] <0.16224.8>@mod_client_state:filter_other:280 Won't add stanza for max@<redacted>.de/gajim.8DJQHROQ to CSI queue
2019-04-18 09:29:31.298 [debug] <0.16224.8>@mod_client_state:dequeue_sender:331 Flushing packets of @upload.<redacted>.de from CSI queue of max@<redacted>.de/gajim.8DJQHROQ
2019-04-18 09:29:31.298 [info] <0.16224.8> (tls|<0.16224.8>) Send XML on stream = <<"<iq xml:lang='en' to='max@<redacted>.de/gajim.8DJQHROQ' from='upload.<redacted>.de' type='result' id='a2e76495-0162-4acf-94e3-2669f81d5287'><slot xmlns='urn:xmpp:http:upload:0'><get url='https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py'/><put url='https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/CUEdTe52Ryj4AlVMmtfkB9Wn3o0ZCfoJqeK3dUI1/entropy.py'/></slot></iq>">>
2019-04-18 09:29:31.298 [info] <0.16224.8> (tls|<0.16224.8>) Send XML on stream = <<"<r xmlns='urn:xmpp:sm:3'/>">>
2019-04-18 09:29:31.318 [info] <0.16224.8> (tls|<0.16224.8>) Received XML on stream = <<"<r xmlns=\"urn:xmpp:sm:3\" />">>
2019-04-18 09:29:31.318 [info] <0.16224.8> (tls|<0.16224.8>) Send XML on stream = <<"<a h='83' xmlns='urn:xmpp:sm:3'/>">>
2019-04-18 09:29:31.337 [debug] <0.16224.8>@mod_stream_mgmt:check_h_attribute:476 max@<redacted>.de/gajim.8DJQHROQ acknowledged 146 of 146 stanzas
2019-04-18 09:29:31.337 [info] <0.16224.8> (tls|<0.16224.8>) Received XML on stream = <<"<a xmlns=\"urn:xmpp:sm:3\" h=\"146\" />">>
2019-04-18 09:29:31.350 [debug] <0.16356.8>@ejabberd_http:init:151 S: [{[<<"upload">>],mod_http_upload}]
2019-04-18 09:29:31.350 [info] <0.370.0>@ejabberd_listener:accept:238 (none) Accepted connection <redacted>:56810 -> <redacted>:5444

```

# gajim debug log
```
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Detected MIME type of file: text/x-python
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: httpupload-progress
04/18/2019 09:34:17 (D) gajim.c.ged Call handler _on_httpupload_progress on <dialogs.ProgressWindow object at 0x7fdc9d62a1f8 (gajim+dialogs+ProgressWindow at 0x2edfca0)>
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Sending request for slot
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: httpupload-progress
04/18/2019 09:34:17 (D) gajim.c.ged Call handler _on_httpupload_progress on <dialogs.ProgressWindow object at 0x7fdc9d62a1f8 (gajim+dialogs+ProgressWindow at 0x2edfca0)>
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-sent
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-sent
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-received
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Received slot
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Uploading file to https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/AwseH1sToIXtJwGqE5yJq0qDNbdoUldUBMRO8TVs/entropy.py
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Please download from https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/AwseH1sToIXtJwGqE5yJq0qDNbdoUldUBMRO8TVs/entropy.py
04/18/2019 09:34:17 (I) gajim.c.m.httpupload Opening Urllib upload request...
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: httpupload-progress
04/18/2019 09:34:17 (D) gajim.c.ged Call handler _on_httpupload_progress on <dialogs.ProgressWindow object at 0x7fdc9d62a1f8 (gajim+dialogs+ProgressWindow at 0x2edfca0)>
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-received
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-sent
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: stanza-received
04/18/2019 09:34:17 (E) gajim.c.m.httpupload URLError
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gajim/common/modules/httpupload.py", line 296, in _upload_file
    transfer = urlopen(request, timeout=30)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] Error>
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: httpupload-progress
04/18/2019 09:34:17 (D) gajim.c.ged Call handler _on_httpupload_progress on <dialogs.ProgressWindow object at 0x7fdc9d62a1f8 (gajim+dialogs+ProgressWindow at 0x2edfca0)>
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: httpupload-progress
04/18/2019 09:34:17 (D) gajim.c.ged Raise event: information
04/18/2019 09:34:17 (D) gajim.c.ged Call handler handle_event_information

```

# conversations debug log (adb logcat)
```
04-18 09:38:19.245 17587 17587 D conversations: ConversationsActivity.commitAttachments() - attaching image to conversations. CHOOSE_IMAGE
04-18 09:38:19.307 17587 17613 D conversations: copy image (content://com.android.providers.media.documents/document/image%3A16334) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/8367f3cc-e65c-4bce-9066-b2be538bf7e4.jpg
04-18 09:38:19.323 17587 17613 D conversations: reading bitmap with sample size 1
04-18 09:38:19.341 17587 17587 D conversations: received uri permission for content://com.android.providers.media.documents/document/image%3A16334
04-18 09:38:19.783 17587 17613 I CameraExif: Unsupported orientation
04-18 09:38:19.870 17587 17613 D conversations: send file message
04-18 09:38:19.895 17587 17592 I zygote64: Do partial code cache collection, code=61KB, data=46KB
04-18 09:38:19.896 17587 17592 I zygote64: After code cache collection, code=61KB, data=46KB
04-18 09:38:19.896 17587 17592 I zygote64: Increasing code cache capacity to 256KB
04-18 09:38:19.898  2569  4132 E NotificationService: Suppressing notification from package by user request.
04-18 09:38:19.900  2569  2665 E NotificationService: Suppressing notification from package by user request.
04-18 09:38:19.919 17587 27281 D conversations: uploading to https://conference.<redacted>.de:5444/upload/4bdbdbf09a0858d3cef53dad11a35457443f543b/xa3Pe34kUuRRdTDzDr6um7epRBvy5ywZYM8tsafU/g2fzzOZcS86QZrK-U4v35A.jpg w/ read timeout of 132s
04-18 09:38:19.942  2569  4132 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@899f76d
04-18 09:38:19.943  2569  4132 I NotificationService: cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@397a725
04-18 09:38:19.943  2569  4132 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@899f76d
04-18 09:38:19.948  2569  2569 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@899f76d
04-18 09:38:20.043 17587 27281 W System.err: javax.net.ssl.SSLHandshakeException: Connection closed by peer
04-18 09:38:20.044 17587 27281 W System.err: 	at org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-18 09:38:20.044 17587 27281 W System.err: 	at org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:393)
04-18 09:38:20.044 17587 27281 W System.err: 	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:225)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
04-18 09:38:20.044 17587 27281 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
04-18 09:38:20.045 17587 27281 W System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
04-18 09:38:20.045 17587 27281 W System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
04-18 09:38:20.045 17587 27281 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:183)
04-18 09:38:20.045 17587 27281 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:30)
04-18 09:38:20.045 17587 27281 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:138)
04-18 09:38:20.045 17587 27281 W System.err: 	at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$xe9LFzy6COS1JMdivVN6RPSpYq4.run(Unknown Source:2)
04-18 09:38:20.045 17587 27281 W System.err: 	at java.lang.Thread.run(Thread.java:764)
04-18 09:38:20.045 17587 27281 D conversations: http upload failed Connection closed by peer
```

# config (stripped for the relevant parts)
```
define_macro:
  'CIPHERS': "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
  'TLSOPTS':
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
    - "no_compression"
listen:
  -
    port: 5444
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/upload": mod_http_upload
    tls: true
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
modules:
  mod_http_upload:
    docroot: "/var/www/ejabberd/upload"
    put_url: "https://conference.<redacted>.de:5444/upload"
    file_mode: "0644"
    dir_mode: "0755"
    thumbnail: true
```

**Comment by zinid** [comment]
So clients are able to log in if you restart them, but http upload doesn't work? Which means the cert is applied to XMPP connections but not to HTTP ones?

**Comment by MEschenbacher** [comment]
Yes, clients will connect but are unable to upload.

**Comment by zinid** [comment]
Well, it's hard to say now what happened because you already have it resolved and cannot reproduce it anymore. But if you can reproduce it: are you able to download some of already uploaded files using a browser? Or, otherwise, you can check the cert via `openssl` command:
```
$ openssl s_client -connect conference.<redacted>.de:5444 | openssl x509 -text -noout
```

**Comment by MEschenbacher** [comment]
I did reproduce it just before opening the issue in order to produce debug logs.
By using your command I am seeing the non-wildcard cert before, and the wildcard cert after reloading ejabberd. I am unable to download already uploaded files from the server via browser or any other client: gajim just does nothing, conversations says `file not found`, firefox says `secure connection failed`

**Comment by MEschenbacher** [comment]
I just did another test by having a fully configured and functioning ejabberd with my wildcard cert:
 - verify uploading works
 - switch to non-wildcard
 - **reload** ejabberd
 - verify uploading **still** works

this is weird but I can reproduce it 100% of the time.

**Comment by zinid** [comment]
> By using your command I am seeing the non-wildcard cert before, and the wildcard cert after reloading ejabberd. I am unable to download already uploaded files from the server via browser or any other client: gajim just does nothing, conversations says file not found, firefox says secure connection failed

These two sounds like a contradiction. So openssl command reports the valid certificate, but firefox says it's invalid?

**Comment by MEschenbacher** [comment]
You are right, I am getting
```
write:errno=0
unable to load certificate
140254157755456:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```
now.

**Comment by zinid** [comment]
This is really weird. Don't you have some proxies in between the server and a client?

**Comment by MEschenbacher** [comment]
Even more weird
```openssl s_client -connect conference.<redacted>.de:5444 | openssl x509 -text -noout
# fails
openssl s_client -connect \[<ipv6>\]:5444 | openssl x509 -text -noout
# succeeds
openssl s_client -connect <ipv4>:5444 | openssl x509 -text -noout
# also succeeds
```

I am using `6tunnel` for incoming ipv4 connectivity on conference.<redacted>.de to tunnel all xmpp ports to the respective VM.

**Comment by zinid** [comment]
I'm not sure I can ask you for more debug info, because it's starting to be unclear whether this is related to ejabberd/certificates or some network/DNS problem.

**Comment by MEschenbacher** [comment]
Yeah, I figure and from your point of view this really might be some convoluted setup problem on my side. Currently, I am pretty confident that this issue can be reproduced by following the steps in my initial post and will try to reproduce them in a clean VM environment. Is this okay for you?

**Comment by zinid** [comment]
> Is this okay for you?

Sure. I obviously want to fix the bug (if any).

**Comment by MEschenbacher** [comment]
I am unable to reproduce the failure when switching from the non-wildcard cert to the wildcard cert in a fresh VM. Thanks for your time and sorry for the noise.
