### ISSUE TITLE
ejabberd 18:09 returns a non-standard SASL error per RFC6120

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#3332]
## Environment

- ejabberd version: 18.09
- Erlang version:
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]
Eshell V9.2  (abort with ^G)
- OS: Linux (Debian) 18.04
- Installed from: source
...

## Bug description
While performing test on aTalk, ejabberd returns a SASL error i.e. \<bad-protocol/> (see aTalk log) not defined in:
[Extensible Messaging and Presence Protocol (XMPP): Core](https://www.rfc-editor.org/rfc/rfc6120.html#section-6.5)

Please refer to the following link for more info
https://discourse.igniterealtime.org/t/smack-4-4-0-alpha-sasl-error-bad-protocol-return-by-ejabberd-is-not-listed-in-smack-enum-saslerror/88393

## aTalk debug.log
```
2020-07-17 11:26:06.530 28946-31195/org.atalk.android D/SMACK: RECV (1): 
    <stream:features>
      <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
        <mechanism>
          EXTERNAL
        </mechanism>
        <mechanism>
          PLAIN
        </mechanism>
        <mechanism>
          SCRAM-SHA-1
        </mechanism>
        <mechanism>
          X-OAUTH2
        </mechanism>
      </mechanisms>
      <register xmlns='http://jabber.org/features/iq-register'/>
    </stream:features>
2020-07-17 11:26:06.562 28946-31194/org.atalk.android D/SMACK: SENT (1): 
    <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='EXTERNAL'>
      c3dvcmRmaXNoQGF0YWxrLnN5dGVzLm5ldA==
    </auth>
2020-07-17 11:26:06.568 28946-31195/org.atalk.android D/SMACK: RECV (1): 
    <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
      <bad-protocol/>
      <text xml:lang='en'>
        Failed to get peer certificate
      </text>
    </failure>
2020-07-17 11:26:06.575 28946-31195/org.atalk.android W/aTalk: [110665] org.jivesoftware.smack.sasl.SASLError.fromString() Could not transform string 'bad_protocol' to SASLError
    java.lang.IllegalArgumentException: No enum constant org.jivesoftware.smack.sasl.SASLError.bad_protocol
        at java.lang.Enum.valueOf(Enum.java:257)
        at org.jivesoftware.smack.sasl.SASLError.valueOf(SASLError.java:27)
        at org.jivesoftware.smack.sasl.SASLError.fromString(SASLError.java:51)
        at org.jivesoftware.smack.sasl.packet.SaslNonza$SASLFailure.<init>(SaslNonza.java:200)
        at org.jivesoftware.smack.provider.SaslFailureProvider.parse(SaslFailureProvider.java:59)
        at org.jivesoftware.smack.provider.SaslFailureProvider.parse(SaslFailureProvider.java:28)
        at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessNonza(AbstractXMPPConnection.java:1429)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1700(XMPPTCPConnection.java:130)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:992)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:898)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:921)
        at java.lang.Thread.run(Thread.java:919)
2020-07-17 11:26:36.268 28946-31195/org.atalk.android D/SMACK: RECV (1): 
    <stream:error>
      <connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
      <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>
        Idle connection
      </text>
    </stream:error>
2020-07-17 11:26:36.288 28946-31211/org.atalk.android W/aTalk: [110667] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (1) closed with error
    org.jivesoftware.smack.XMPPException$StreamErrorException: connection-timeout You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
    <stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='en'>Idle connection</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:966)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:898)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:921)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by mremond** [comment]
Actually, it seems not of the value define in the standard matches the errors we are reporting here with bad-protocol.

The following cases are not defined in the RFC:
- Remote domain is not an IDN hostname
- Failed to get peer certificate

If we want to fit the spec, we will have to use the generic "not-authorized".

**Comment by prefiks** [comment]
I changed all bad-protocol results (which seems as remanants from pre-rfc xmpp code), to return something that is ok by spec.
