### ISSUE TITLE
Segmentation fault (core dumped) of benchmark ejabberd with tsung 

### ISSUE THREAD

**Issue by developerworks** [processone/ejabberd#478]
Tsung conf:

```xml
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd">
<tsung loglevel="debug" dumptraffic="false" version="1.0">
    <clients>
        <client host="scm" maxusers="200000">
            <ip value="192.168.8.200"></ip>
        </client>
        <client host="compile" maxusers="200000">
            <ip value="192.168.8.31"></ip>
        </client>
    </clients>
    <servers>
        <server host='master.hezhiqiang.info' port='5222' type='tcp'/>
    </servers>
    <load>
        <arrivalphase phase="1" duration="1800" unit="second">
            <users maxnumber="200000" interarrival="0.002" unit="second"></users>
        </arrivalphase>
    </load>
    <options>
        <option type="ts_jabber" name="global_number" value="100000"></option>
        <option type="ts_jabber" name="userid_max" value="100000"></option>
        <option type="ts_jabber" name="domain" value="master.hezhiqiang.info"></option>
        <option type="ts_jabber" name="username" value="u"></option>
        <option type="ts_jabber" name="passwd" value="p"></option>
        <option name="ports_range" min="1025" max="65535"/>
    </options>
    <sessions>
        <session probability="100" name="jabber-example" type="ts_jabber">
            <request>
                <jabber type="connect" ack="local"></jabber>
            </request>
            <request>
                <match do="abort" when="match">error</match>
                <jabber type="register" ack="local" id="new"></jabber>
            </request>
            <thinktime value="600"></thinktime>
            <request>
                <jabber type="close" ack="local"></jabber>
            </request>
        </session>
    </sessions>
</tsung>
```

Error:

```
15:47:01.846 [info] (#Port<0.20783>) Accepted connection 192.168.8.200:6444 -> 192.168.8.33:5222
15:47:01.847 [info] (#Port<0.20785>) Accepted connection 192.168.8.31:4422 -> 192.168.8.33:5222
15:47:01.854 [info] (#Port<0.20787>) Accepted connection 192.168.8.200:6447 -> 192.168.8.33:5222
15:47:01.859 [info] (#Port<0.20789>) Accepted connection 192.168.8.200:6371 -> 192.168.8.33:5222
15:47:01.862 [info] (#Port<0.20791>) Accepted connection 192.168.8.200:6457 -> 192.168.8.33:5222
15:47:01.863 [info] (#Port<0.20793>) Accepted connection 192.168.8.31:4684 -> 192.168.8.33:5222
15:47:01.865 [info] (#Port<0.20795>) Accepted connection 192.168.8.31:4928 -> 192.168.8.33:5222
15:47:01.872 [info] (#Port<0.20797>) Accepted connection 192.168.8.31:6544 -> 192.168.8.33:5222
15:47:01.874 [info] (#Port<0.20799>) Accepted connection 192.168.8.31:6489 -> 192.168.8.33:5222
15:47:01.878 [info] (#Port<0.20801>) Accepted connection 192.168.8.31:6547 -> 192.168.8.33:5222
15:47:01.880 [info] (#Port<0.20803>) Accepted connection 192.168.8.200:4498 -> 192.168.8.33:5222
15:47:01.884 [info] (#Port<0.20805>) Accepted connection 192.168.8.31:6549 -> 192.168.8.33:5222
15:47:01.886 [info] (#Port<0.20807>) Accepted connection 192.168.8.200:6206 -> 192.168.8.33:5222
15:47:01.887 [info] (#Port<0.20809>) Accepted connection 192.168.8.200:2257 -> 192.168.8.33:5222
15:47:01.887 [info] (#Port<0.20811>) Accepted connection 192.168.8.31:6553 -> 192.168.8.33:5222
15:47:01.891 [info] (#Port<0.20813>) Accepted connection 192.168.8.31:6302 -> 192.168.8.33:5222
15:47:01.900 [info] (#Port<0.20815>) Accepted connection 192.168.8.200:6207 -> 192.168.8.33:5222
15:47:01.903 [info] (#Port<0.20817>) Accepted connection 192.168.8.200:6157 -> 192.168.8.33:5222
15:47:01.907 [info] (#Port<0.20819>) Accepted connection 192.168.8.31:6304 -> 192.168.8.33:5222
15:47:01.913 [info] (#Port<0.20821>) Accepted connection 192.168.8.200:6470 -> 192.168.8.33:5222
15:47:01.914 [info] (#Port<0.20823>) Accepted connection 192.168.8.200:4661 -> 192.168.8.33:5222
Segmentation fault (core dumped)
```

**Comment by mremond** [comment]
Honestly, this is too low in details to be an actionable ticket. You do not even say anything about your environment, do not provide segfault info. I am very sorry, but there is nothing we can conclude from your report.

**Comment by developerworks** [comment]
No crash dumps
How to generate os core dump ?

**Comment by mremond** [comment]
Here is a document explaining how to find core on Linux and check why they are not generated: http://www.fromdual.com/hunting-the-core

Here is a stackoverflow comment on how to analyse the core:
http://stackoverflow.com/a/8306805/559289

**Comment by developerworks** [comment]
I found the following error messages in dmesg.

```
root@ci:/proc/sys/net/netfilter# dmesg 
[3742448.699075] TCP: TCP: Possible SYN flooding on port 5222. Dropping request.  Check SNMP counters.
[3742466.649968] beam.smp[8639]: segfault at 6ff1f10c8718 ip 00000000004f134a sp 00007ff1f2a3c960 error 6 in beam.smp[400000+200000]
[3742613.115240] TCP: TCP: Possible SYN flooding on port 5222. Dropping request.  Check SNMP counters.
[3742658.977911] TCP: TCP: Possible SYN flooding on port 5222. Dropping request.  Check SNMP counters.
[3742730.912406] traps: beam.smp[9039] general protection ip:441c95 sp:7fef9e07bb80 error:0 in beam.smp[400000+200000]
```

**Comment by mremond** [comment]
You have to analyse the core with the method describe in the link. You cannot know the reason without digging into the binary symbol with gdb.

I would also try with another Erlang version as it is the Erlang VM crashing.

**Comment by developerworks** [comment]
```
root@ci:/var/lib/ejabberd# gdb /usr/lib/erlang/erts-6.2/bin/beam.smp -c core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/erlang/erts-6.2/bin/beam.smp...(no debugging symbols found)...done.
[New LWP 29204]
[New LWP 29208]
[New LWP 29193]
[New LWP 29190]
[New LWP 29195]
[New LWP 29194]
[New LWP 29198]
[New LWP 29197]
[New LWP 29191]
[New LWP 29200]
[New LWP 29199]
[New LWP 29201]
[New LWP 29202]
[New LWP 29192]
[New LWP 29203]
[New LWP 29206]
[New LWP 29196]
[New LWP 29207]
[New LWP 29205]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/erlang/erts-6.2/bin/beam.smp -K true -P 10485760 -- -root /usr/lib/erl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000468be2 in size_object ()
(gdb) bt
#0  0x0000000000468be2 in size_object ()
#1  0x000000000048f422 in erts_send_message ()
#2  0x0000000000475c0e in do_send ()
#3  0x0000000000476560 in erl_send ()
#4  0x000000000052b3da in process_main ()
#5  0x00000000004909af in ?? ()
#6  0x0000000000595875 in ?? ()
#7  0x00007fc7f617f182 in start_thread (arg=0x7fc7db8bf700) at pthread_create.c:312
#8  0x00007fc7f5ca400d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
