### ISSUE TITLE
SSL Handshake failing sometimes

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#854]
Hey guys,

I am using smack 4.2.0 with ejabberd-15.09 and I am getting this issue sometimes. While retrying it's able to connect. I found a similar issue - https://github.com/processone/ejabberd/issues/679 which is closed.
```
 <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'></starttls>
D/SMACK   (  941): RECV (0): <stream:features><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='QUCoEHqJByuYfk1DDzl++S6juDE='/><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls><compression xmlns='http://jabber.org/features/compress'><method>zlib</method></compression></stream:features>
D/SMACK   (  941): SENT (0): <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'></starttls>
D/SMACK   (  941): RECV (0): <proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:989)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
W/AbstractXMPPConnection(  941): Connection XMPPTCPConnection[47b26291-626f-41f2-a73a-91f3b391d8b3@ejabberd.sandwitch.in/smack] (0) closed with error
W/AbstractXMPPConnection(  941): javax.net.ssl.SSLHandshakeException: Connection closed by peer
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:598)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:560)
W/AbstractXMPPConnection(  941): 	at crittercism.android.aa.getInputStream(Unknown Source)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
W/AbstractXMPPConnection(  941): 	at java.lang.Thread.run(Thread.java:818)
D/SMACK   (  941): XMPPConnection closed due to an exception (XMPPTCPConnection[47b26291-626f-41f2-a73a-91f3b391d8b3@ejabberd.sandwitch.in/smack] (0))
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
D/XMPPManager(  941): scheduleReconnect: scheduling reconnect in 10 seconds
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:989)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
W/System.err(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
W/AbstractXMPPConnection(  941): Connection XMPPTCPConnection[47b26291-626f-41f2-a73a-91f3b391d8b3@ejabberd.sandwitch.in/smack] (0) closed with error
W/AbstractXMPPConnection(  941): javax.net.ssl.SSLHandshakeException: Handshake failed
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:598)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:560)
W/AbstractXMPPConnection(  941): 	at crittercism.android.aa.getInputStream(Unknown Source)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
W/AbstractXMPPConnection(  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
W/AbstractXMPPConnection(  941): 	at java.lang.Thread.run(Thread.java:818)
W/AbstractXMPPConnection(  941): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8e35668: Failure in SSL library, usually a protocol error
W/AbstractXMPPConnection(  941): error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number (external/openssl/ssl/s3_pkt.c:338 0xae6f9edd:0x00000000)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/AbstractXMPPConnection(  941): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
W/AbstractXMPPConnection(  941): 	... 10 more
D/SMACK   (  941): XMPPConnection closed due to an exception (XMPPTCPConnection[47b26291-626f-41f2-a73a-91f3b391d8b3@ejabberd.sandwitch.in/smack] (0))
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:630)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:724)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:144)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:982)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:916)
D/SMACK   (  941): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:931)
D/XMPPManager(  941): scheduleReconnect: scheduling reconnect in 10 seconds
```

**Comment by weiss** [comment]
This is the actual error message you might want to search the web for:

    SSL3_GET_RECORD:wrong version number

Can you reproduce the problem if you don't set any TLS `protocol_options` in ejabberd?

> While retrying it's able to connect.

You might have to watch the both cases (failure and success) with tcpdump/wireshark in order to track the issue down.

**Comment by bangarharshit** [comment]
Thanks. I am not setting any protocol_options so default no_sslv2 must be used. I will try to track it through tcpdump

**Comment by rraptorr** [comment]
SSL 3.0 is unsecure, broken and disabled by more than half of the Internet already;) You really should use only TLS 1.0, 1.1 and 1.2. See https://tools.ietf.org/html/rfc7568 for details.

**Comment by bangarharshit** [comment]
Unable to reproduce the issue so closing it.
